---
- hosts: prod-servers
  remote_user: root

  vars:
    # tomcat_package_url: http://mirrors.cnnic.cn/apache/tomcat/tomcat-7/v7.0.63/bin/apache-tomcat-7.0.63.tar.gz
    # tomcat_version: 7.0.63
    tomcat_package_url: http://mirrors.cnnic.cn/apache/tomcat/tomcat-8/v8.0.24/bin/apache-tomcat-8.0.24.tar.gz
    tomcat_version: 8.0.24

  tasks:
    - name: Install java-1.7.0-openjdk
      yum: name=java-1.7.0-openjdk state=present

    - name: Download Tomcat Package
      get_url: url={{tomcat_package_url}} dest=/opt/apache-tomcat-{{tomcat_version}}.tar.gz

    - name: Extract Tomcat Package
      unarchive: src=/opt/apache-tomcat-{{tomcat_version}}.tar.gz dest=/opt copy=no

    - name: Install Tomcat Init Script
      copy: src=files/tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

    - name: Symlink tomcat install directory
      file: src=/opt/apache-tomcat-{{tomcat_version}} path=/opt/apache-tomcat state=link

    - name: Start Tomcat
      service: name=tomcat state=started enabled=yes

    - name: Push Artifact to Remote Host
      copy: src=/home/devops/.jenkins/jobs/temp/workspace/build/libs/workspace.war dest=/opt/apache-tomcat/webapps/SuperCalculator.war force=yes
